#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

VERSION=$1

if [ -z "$VERSION" ]; then
  CURRENT_VERSION=$(node -pe "require('./package.json').version")
  VERSION=$(npx --no-install semver -i minor $CURRENT_VERSION)
fi

echo $VERSION
exit 0